.Dd August 28, 2023
.Dt XCANDB 1
.Sh NAME
.Nm xcandb
.Nd image crop and blur utility for X
.Sh SYNOPSIS
.Nm
.Op Fl fhv
.Op Fl l Ar file
.Sh DESCRIPTION
The
.Nm
application lets you crop images with ease.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl f
start in fullscreen mode
.It Fl h
show usage
.It Fl v
display the program version
.It Fl l
load image from path
.El
.Sh EXAMPLES
.Bl -tag -width indent
.It crop and blur a freshly taken screenshot
xcandb -f -l $(xscreenshot -p -d $(mktemp -d))
.El
.Sh KEYBOARD BINDINGS
.Bl -tag -width indent
.It Ctrl+s
Save result image to disk.
.El
.Sh MOUSE BINDINGS
.Bl -tag -width indent
.It Left Mouse Button
Crop.
.It Right Mouse Button
Blur.
.El
.Sh SEE ALSO
.Xr X 7
.Xr xscreenshot 1
.Xr imgcrop 1
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/xcandb/issues
